"""Add Provenance table

Revision ID: 10b99c88f819
Revises: 7e980e3d922e
Create Date: 2026-09-13 08:11:10.448364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10b99c88f819'
down_revision: Union[str, Sequence[str], None] = '7e980e3d922e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provenance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('target_field', sa.String(), nullable=False),
    sa.Column('source_field', sa.String(), nullable=False),
    sa.Column('source_value', sa.String(), nullable=True),
    sa.Column('transformation', sa.String(), nullable=False),
    sa.Column('mapping_id', sa.String(), nullable=True),
    sa.Column('mapping_version', sa.Integer(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provenance_records'))
    )
    with op.batch_alter_table('provenance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provenance_records_trace_id'), ['trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provenance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provenance_records_trace_id'))

    op.drop_table('provenance_records')
    # ### end Alembic commands ###
