"""multi_tenancy_and_rbac

Revision ID: 670342bd0299
Revises: a1b2c3d4e5f6
Create Date: 2026-09-11 16:26:50.326462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670342bd0299'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tenant_table = op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    user_table = op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )

    import datetime
    op.bulk_insert(tenant_table, [
        {"id": "default", "name": "Default Tenant", "created_at": datetime.datetime.utcnow()}
    ])
    from passlib.context import CryptContext
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
    import uuid
    from app.core.config import settings
    op.bulk_insert(user_table, [
        {
            "id": str(uuid.uuid4()), 
            "tenant_id": "default", 
            "username": settings.ADMIN_USERNAME, 
            "password_hash": pwd_context.hash(settings.ADMIN_PASSWORD), 
            "role": "administrator",
            "created_at": datetime.datetime.utcnow()
        }
    ])
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(), server_default=sa.text("'default'"), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_api_keys_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(), server_default=sa.text("'default'"), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_ingestion_jobs_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('ingestion_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(), server_default=sa.text("'default'"), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_ingestion_sessions_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('onboarding_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(), server_default=sa.text("'default'"), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_onboarding_sessions_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('rule_locks', schema=None) as batch_op:
        batch_op.alter_column('events_since_lock',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('events_since_mismatch',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(), server_default=sa.text("'default'"), nullable=False))
        batch_op.drop_index(batch_op.f('ix_unique_active_rule_version'), sqlite_where=sa.text("status = 'ACTIVE'"))
        batch_op.create_foreign_key(batch_op.f('fk_rule_versions_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(), server_default=sa.text("'default'"), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_rules_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(), server_default=sa.text("'default'"), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_sources_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sources_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rules_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rule_versions_tenant_id_tenants'), type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_unique_active_rule_version'), ['rule_id'], unique=1, sqlite_where=sa.text("status = 'ACTIVE'"))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('rule_locks', schema=None) as batch_op:
        batch_op.alter_column('events_since_mismatch',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('events_since_lock',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('onboarding_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_onboarding_sessions_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('ingestion_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ingestion_sessions_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ingestion_jobs_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_api_keys_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
