"""Add ingestion_session metrics

Revision ID: 7e980e3d922e
Revises: a528f8416dbd
Create Date: 2026-09-12 23:03:03.792375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e980e3d922e'
down_revision: Union[str, Sequence[str], None] = 'a528f8416dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_events', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_events', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('normalized_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unresolved_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('ingestion_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_events', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_events', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('normalized_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unresolved_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('normalized_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_normalized_events_session_id_ingestion_sessions'), 'ingestion_sessions', ['session_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_normalized_events_job_id_ingestion_jobs'), 'ingestion_jobs', ['job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normalized_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_normalized_events_job_id_ingestion_jobs'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_normalized_events_session_id_ingestion_sessions'), type_='foreignkey')
        batch_op.drop_column('session_id')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('ingestion_sessions', schema=None) as batch_op:
        batch_op.drop_column('unresolved_count')
        batch_op.drop_column('normalized_count')
        batch_op.drop_column('processed_events')
        batch_op.drop_column('total_events')

    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_column('unresolved_count')
        batch_op.drop_column('normalized_count')
        batch_op.drop_column('processed_events')
        batch_op.drop_column('total_events')

    # ### end Alembic commands ###
