"""Add one_active_version_per_rule index

Revision ID: a528f8416dbd
Revises: 670342bd0299
Create Date: 2026-09-12 21:58:34.713848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a528f8416dbd'
down_revision: Union[str, Sequence[str], None] = '670342bd0299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.create_index('one_active_version_per_rule', ['rule_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_index('one_active_version_per_rule', postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))

    # ### end Alembic commands ###
