"""Initial schema

Revision ID: a77e76a98af3
Revises: 44182199df93
Create Date: 2026-08-29 16:15:15.664827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77e76a98af3'
down_revision: Union[str, Sequence[str], None] = '44182199df93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.add_column('sources', sa.Column('active_mapping_version', sa.Integer(), nullable=True))
    op.create_table('files',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_status', sa.String(), nullable=False),
    sa.Column('trace_ids', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('mapping_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_column('sources', 'active_mapping_version')
    op.drop_column('sources', 'last_seen_at')
    # ### end Alembic commands ###
