"""Add job and session tracking

Revision ID: c0eee8335003
Revises: 6ab1270fd438
Create Date: 2026-09-09 13:21:58.109798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0eee8335003'
down_revision: Union[str, Sequence[str], None] = '6ab1270fd438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normalized_events', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_normalized_events_job_id_ingestion_jobs'), 'ingestion_jobs', ['job_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_normalized_events_session_id_ingestion_sessions'), 'ingestion_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('raw_index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_raw_index_job_id_ingestion_jobs'), 'ingestion_jobs', ['job_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_raw_index_session_id_ingestion_sessions'), 'ingestion_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('rule_locks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fingerprint', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sample_count_seen', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mismatch_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_rule_locks_job_id_ingestion_jobs'), 'ingestion_jobs', ['job_id'], ['id'])

    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_traces_session_id_ingestion_sessions'), 'ingestion_sessions', ['session_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_traces_job_id_ingestion_jobs'), 'ingestion_jobs', ['job_id'], ['id'])

    with op.batch_alter_table('unresolved_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_unresolved_events_session_id_ingestion_sessions'), 'ingestion_sessions', ['session_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_unresolved_events_job_id_ingestion_jobs'), 'ingestion_jobs', ['job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unresolved_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_unresolved_events_job_id_ingestion_jobs'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_unresolved_events_session_id_ingestion_sessions'), type_='foreignkey')
        batch_op.drop_column('session_id')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_traces_job_id_ingestion_jobs'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_traces_session_id_ingestion_sessions'), type_='foreignkey')
        batch_op.drop_column('session_id')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('rule_locks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rule_locks_job_id_ingestion_jobs'), type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('mismatch_count')
        batch_op.drop_column('sample_count_seen')
        batch_op.drop_column('fingerprint')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('raw_index', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_raw_index_session_id_ingestion_sessions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_raw_index_job_id_ingestion_jobs'), type_='foreignkey')
        batch_op.drop_column('session_id')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('normalized_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_normalized_events_session_id_ingestion_sessions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_normalized_events_job_id_ingestion_jobs'), type_='foreignkey')

    # ### end Alembic commands ###
