"""Initial V2 Schema

Revision ID: ce05c64e3a13
Revises: 
Create Date: 2026-09-08 19:40:41.243490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce05c64e3a13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('rules',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('schema_versions',
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('field_definitions', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('compatibility_class', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('schema_version')
    )
    op.create_table('sources',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('transport', sa.String(), nullable=False),
    sa.Column('format_hint', sa.String(), nullable=True),
    sa.Column('namespace', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('dead_letters',
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('error_class', sa.String(), nullable=False),
    sa.Column('diagnostic', sa.String(), nullable=False),
    sa.Column('raw_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.rule_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_index',
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('transport', sa.String(), nullable=False),
    sa.Column('peer', sa.String(), nullable=True),
    sa.Column('byte_length', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_table('rule_fingerprints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.rule_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parser_type', sa.String(), nullable=False),
    sa.Column('parser_definition', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('field_mappings', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('required_fields', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('type_constraints', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('masking_policy', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('target_schema', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('rule_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.rule_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traces',
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('rule_version', sa.Integer(), nullable=True),
    sa.Column('rule_hash', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.rule_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_table('normalized_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('rule_version', sa.Integer(), nullable=True),
    sa.Column('processing_path', sa.String(), nullable=False),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.rule_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.trace_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('rule_approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_version_id', sa.String(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_lifecycle_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('rule_version_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.rule_id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_llm_generations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_version_id', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('response_json', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_locks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('rule_version_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ingestion_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_test_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_version_id', sa.String(), nullable=False),
    sa.Column('raw_sample', sa.String(), nullable=False),
    sa.Column('expected_output', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_validation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_version_id', sa.String(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unresolved_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.trace_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unresolved_events')
    op.drop_table('rule_validation_runs')
    op.drop_table('rule_test_cases')
    op.drop_table('rule_locks')
    op.drop_table('rule_llm_generations')
    op.drop_table('rule_lifecycle_events')
    op.drop_table('rule_approvals')
    op.drop_table('normalized_events')
    op.drop_table('traces')
    op.drop_table('rule_versions')
    op.drop_table('rule_fingerprints')
    op.drop_table('raw_index')
    op.drop_table('onboarding_sessions')
    op.drop_table('ingestion_sessions')
    op.drop_table('ingestion_jobs')
    op.drop_table('dead_letters')
    op.drop_table('sources')
    op.drop_table('schema_versions')
    op.drop_table('rules')
    op.drop_table('audit')
    # ### end Alembic commands ###
