import logging
import uuid
from datetime import datetime
from typing import Any

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.authoring.agent import generate_rule_from_samples
from app.core.auth import get_current_user
from app.core.database import get_db
from app.models.domain import OnboardingSession, RuleVersion
from app.services.rules.fingerprint import generate_fingerprint
from app.services.rules.parsers.base import ParserError
from app.services.rules.parsers.factory import ParserFactory
from app.services.rules.registry import (
    add_fingerprint_to_rule,
    create_rule,
    create_rule_version,
    find_active_rule_by_fingerprint,
    update_rule_version_status,
)

router = APIRouter(prefix="/onboarding", tags=["Onboarding"])
logger = logging.getLogger(__name__)

def _get_session(db: Session, session_id: str) -> OnboardingSession:
    s = db.query(OnboardingSession).filter(OnboardingSession.id == session_id).first()
    if not s:
        raise HTTPException(status_code=404, detail="Session not found")
    return s

@router.post("", status_code=201)
def create_session(payload: dict[str, Any], db: Session = Depends(get_db)):
    source_id = payload.get("source_id")
    if not source_id:
        raise HTTPException(status_code=400, detail="source_id is required")
        
    from app.models.domain import Source
    source = db.query(Source).filter(Source.source_id == source_id).first()
    if not source:
        raise HTTPException(status_code=404, detail=f"Source '{source_id}' does not exist. Create it first via POST /sources.")
        
    session_id = str(uuid.uuid4())
    session = OnboardingSession(
        id=session_id,
        source_id=source_id,
        status="STARTED",
    )
    db.add(session)
    db.commit()
    return {"session_id": session.id, "status": session.status}

@router.post("/{session_id}/samples")
def upload_samples(session_id: str, samples: list[str], db: Session = Depends(get_db)):
    session = _get_session(db, session_id)
    if not samples or len(samples) < 1:
        raise HTTPException(status_code=400, detail="At least 1 sample is required")
        
    fingerprint = generate_fingerprint(samples[0])
    session.fingerprint = fingerprint
    
    active_rule = find_active_rule_by_fingerprint(db, fingerprint)
    
    session.status = "SAMPLES_RECEIVED"
    db.commit()
    
    return {
        "fingerprint": fingerprint,
        "active_rule_found": active_rule is not None,
        "active_rule_id": active_rule.rule_id if active_rule else None
    }

@router.post("/{session_id}/draft")
def generate_draft_rule(session_id: str, samples: list[str], db: Session = Depends(get_db)):
    session = _get_session(db, session_id)
    if not session.fingerprint:
        session.fingerprint = generate_fingerprint(samples[0])
        
    # Invoke local LLM
    try:
        rule_json = generate_rule_from_samples(samples)
    except Exception as e:
        logger.error(f"LLM Generation failed: {e}")
        raise HTTPException(status_code=500, detail=f"LLM generation failed: {e}")
        
    # Create rule and version
    rule_name = f"AutoRule-{session.source_id}-{datetime.utcnow().strftime('%Y%m%d')}"
    rule = create_rule(db, rule_name, "Generated by Local LLM")
    
    version = create_rule_version(
        db=db,
        rule_id=rule.rule_id,
        parser_type=rule_json.get("parser", {}).get("type", "regex"),
        parser_definition=rule_json.get("parser", {}),
        field_mappings=rule_json.get("field_mappings", {}),
        required_fields=rule_json.get("required_fields", []),
        type_constraints=rule_json.get("type_constraints", {}),
        target_schema=rule_json.get("target_schema", "ocsf"),
        schema_version=rule_json.get("schema_version", "1.0"),
    )
    
    add_fingerprint_to_rule(db, rule.rule_id, session.fingerprint)
    
    session.rule_id = rule.rule_id
    session.status = "DRAFT_CREATED"
    db.commit()
    
    return {
        "rule_id": rule.rule_id,
        "version": version.version,
        "rule_json": rule_json
    }

@router.post("/{session_id}/validate")
def validate_rule(session_id: str, payload: dict[str, Any], db: Session = Depends(get_db)):
    """Validates the rule against the samples to ensure it extracts fields correctly and deterministically"""
    session = _get_session(db, session_id)
    if not session.rule_id:
        raise HTTPException(status_code=400, detail="No rule associated with session")
        
    rule_version_id = payload.get("rule_version_id")
    samples = payload.get("samples", [])
    
    version = db.query(RuleVersion).filter(RuleVersion.id == rule_version_id).first()
    if not version:
        raise HTTPException(status_code=404, detail="Rule version not found")
        
    results = []
    passed = True
    
    try:
        parser = ParserFactory.create(version.parser_type, version.parser_definition, version.field_mappings)
        for s in samples:
            try:
                extracted = parser.parse(s)
                # Check required fields
                missing = [f for f in version.required_fields if f not in extracted] if version.required_fields else []
                if missing:
                    passed = False
                    results.append({"sample": s, "extracted": extracted, "error": f"Missing required fields: {missing}"})
                else:
                    results.append({"sample": s, "extracted": extracted, "status": "ok"})
            except ParserError as e:
                passed = False
                results.append({"sample": s, "error": str(e)})
    except Exception as e:
        passed = False
        results.append({"error": str(e)})
        
    if passed:
        update_rule_version_status(db, version.id, "PENDING_REVIEW", "system_validator")
        session.status = "VALIDATION_PASSED"
    else:
        session.status = "VALIDATION_FAILED"
        
    db.commit()
    return {"passed": passed, "results": results, "status": session.status}

@router.post("/{session_id}/approve")
def approve_rule(session_id: str, payload: dict[str, Any], db: Session = Depends(get_db), user: dict = Depends(get_current_user)):
    session = _get_session(db, session_id)
    rule_version_id = payload.get("rule_version_id")
    
    version = db.query(RuleVersion).filter(RuleVersion.id == rule_version_id).first()
    if not version:
        raise HTTPException(status_code=404, detail="Rule version not found")
        
    if version.status != "PENDING_REVIEW":
        raise HTTPException(status_code=400, detail=f"Cannot approve rule in status: {version.status}")
        
    update_rule_version_status(db, version.id, "ACTIVE", "human_reviewer")
    session.status = "COMPLETED"
    session.completed_at = datetime.utcnow()
    db.commit()
    
    return {"status": "ACTIVE", "rule_id": version.rule_id, "version": version.version}
