import logging
import uuid
from datetime import datetime
from typing import Any

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.authoring.agent import generate_rule_from_samples
from app.core.auth import get_current_user
from app.core.database import get_db
from app.models.domain import OnboardingSession, RuleVersion
from app.services.rules.fingerprint import generate_fingerprint
from app.services.rules.parsers.base import ParserError
from app.services.rules.parsers.factory import ParserFactory
from app.services.rules.registry import (
    add_fingerprint_to_rule,
    create_rule,
    create_rule_version,
    find_active_rule_by_fingerprint,
    update_rule_version_status,
)
from app.services.normalization.engine import normalization_engine
from app.authoring.agent import USE_MOCK

router = APIRouter(prefix="/onboarding", tags=["Onboarding"])
logger = logging.getLogger(__name__)

def _get_session(db: Session, session_id: str) -> OnboardingSession:
    s = db.query(OnboardingSession).filter(OnboardingSession.id == session_id).first()
    if not s:
        raise HTTPException(status_code=404, detail="Session not found")
    return s

@router.post("", status_code=201)
def create_session(payload: dict[str, Any], db: Session = Depends(get_db)):
    source_id = payload.get("source_id")
    if not source_id:
        raise HTTPException(status_code=400, detail="source_id is required")
        
    from app.models.domain import Source
    source = db.query(Source).filter(Source.source_id == source_id).first()
    if not source:
        raise HTTPException(status_code=404, detail=f"Source '{source_id}' does not exist. Create it first via POST /sources.")
        
    session_id = str(uuid.uuid4())
    session = OnboardingSession(
        id=session_id,
        source_id=source_id,
        status="STARTED",
    )
    db.add(session)
    db.commit()
    return {"session_id": session.id, "status": session.status}

@router.post("/{session_id}/samples")
def upload_samples(session_id: str, samples: list[str], db: Session = Depends(get_db)):
    session = _get_session(db, session_id)
    if not samples or len(samples) < 1:
        raise HTTPException(status_code=400, detail="At least 1 sample is required")
        
    fingerprint = generate_fingerprint(samples[0])
    session.fingerprint = fingerprint
    
    active_rule = find_active_rule_by_fingerprint(db, fingerprint)
    
    session.status = "SAMPLES_RECEIVED"
    db.commit()
    
    return {
        "fingerprint": fingerprint,
        "active_rule_found": active_rule is not None,
        "active_rule_id": active_rule.rule_id if active_rule else None
    }

@router.post("/{session_id}/draft")
def generate_draft_rule(session_id: str, samples: list[str], db: Session = Depends(get_db)):
    session = _get_session(db, session_id)
    if not session.fingerprint:
        session.fingerprint = generate_fingerprint(samples[0])
        
    # Invoke local LLM
    try:
        rule_json = generate_rule_from_samples(samples)
    except Exception as e:
        logger.error(f"LLM Generation failed: {e}")
        raise HTTPException(status_code=500, detail=f"LLM generation failed: {e}")
        
    # Create rule and version
    rule_name = f"AutoRule-{session.source_id}-{datetime.utcnow().strftime('%Y%m%d')}"
    rule = create_rule(db, rule_name, "Generated by Local LLM")
    
    version = create_rule_version(
        db=db,
        rule_id=rule.rule_id,
        parser_type=rule_json.get("parser", {}).get("type", "regex"),
        parser_definition=rule_json.get("parser", {}),
        field_mappings=rule_json.get("field_mappings", {}),
        required_fields=rule_json.get("required_fields", []),
        type_constraints=rule_json.get("type_constraints", {}),
        target_schema=rule_json.get("target_schema", "ocsf"),
        schema_version=rule_json.get("schema_version", "1.0"),
    )
    
    add_fingerprint_to_rule(db, rule.rule_id, session.fingerprint)
    
    session.rule_id = rule.rule_id
    session.status = "DRAFT_CREATED"
    db.commit()
    
    return {
        "rule_id": rule.rule_id,
        "version": version.id,
        "rule_json": rule_json,
        "llm_mode": "mock" if USE_MOCK else "local_llm"
    }

@router.post("/{session_id}/validate")
async def validate_rule(session_id: str, payload: dict[str, Any], db: Session = Depends(get_db)):
    """Validates the rule against the samples to ensure it extracts fields correctly and deterministically"""
    session = _get_session(db, session_id)
    rule_version_id = payload.get("rule_version_id")
    samples = payload.get("samples", [])
    
    version = db.query(RuleVersion).filter(RuleVersion.id == rule_version_id).first()
    if not version:
        raise HTTPException(status_code=404, detail="Rule version not found")
        
    if not session.rule_id:
        session.rule_id = version.rule_id
        db.commit()
        
    results = []
    passed = True
    
    try:
        parser = ParserFactory.create(version.parser_type, version.parser_definition, version.field_mappings)
        for s in samples:
            import uuid
            from datetime import datetime
            from app.models.domain import RawIndex, UnresolvedEvent
            from app.services.preservation.vault import vault
            
            trace_id = str(uuid.uuid4())
            received_at = datetime.utcnow()
            payload = s.encode('utf-8')
            
            digest_str, vault_path = await vault.write_event(
                trace_id=trace_id,
                source_id=session.source_id,
                payload=payload,
                received_at=received_at
            )
            
            raw_idx = RawIndex(
                trace_id=trace_id,
                source_id=session.source_id,
                transport="studio_test",
                byte_length=len(payload),
                digest=digest_str,
                storage_uri=vault_path,
                received_at=received_at
            )
            db.add(raw_idx)
            
            try:
                extracted = parser.parse(s)
                # Check required fields
                missing = [f for f in version.required_fields if f not in extracted] if version.required_fields else []
                if missing:
                    passed = False
                    results.append({"sample": s, "extracted": extracted, "error": f"Missing required fields: {missing}"})
                    unres = UnresolvedEvent(id=str(uuid.uuid4()), trace_id=trace_id, fingerprint=session.fingerprint)
                    db.add(unres)
                else:
                    normalized_pydantic, _ = normalization_engine.normalize(
                        db=db,
                        parsed_data=extracted,
                        source_id=session.source_id,
                        template_id=rule_version_id,
                        trace_id=trace_id,
                        raw_ref={}
                    )
                    
                    from app.models.domain import Trace
                    from app.models.domain import NormalizedEvent as NormalizedEventORM
                    
                    trace_obj = Trace(
                        trace_id=trace_id,
                        source_id=session.source_id,
                        rule_id=version.rule_id,
                        rule_version=version.version,
                        rule_hash=version.rule_hash,
                        schema_version=version.schema_version
                    )
                    db.add(trace_obj)
                    db.flush()
                    
                    norm_payload = normalized_pydantic.dict()
                    norm_event = NormalizedEventORM(
                        event_id=trace_id + "-n",
                        trace_id=trace_id,
                        source_id=session.source_id,
                        schema_version=version.schema_version,
                        rule_id=version.rule_id,
                        rule_version=version.version,
                        processing_path="studio_test",
                        normalized_payload=norm_payload
                    )
                    db.add(norm_event)
                    
                    results.append({"sample": s, "extracted": extracted, "normalized_payload": norm_payload, "status": "ok"})
            except ParserError as e:
                passed = False
                results.append({"sample": s, "error": str(e)})
                unres = UnresolvedEvent(id=str(uuid.uuid4()), trace_id=trace_id, fingerprint=session.fingerprint)
                db.add(unres)
    except Exception as e:
        passed = False
        results.append({"error": str(e)})
        
    if passed:
        update_rule_version_status(db, version.id, "PENDING_REVIEW", "system_validator")
        session.status = "VALIDATION_PASSED"
    else:
        session.status = "VALIDATION_FAILED"
        
    db.commit()
    return {"passed": passed, "results": results, "status": session.status}

@router.post("/{session_id}/approve")
async def approve_rule(session_id: str, payload: dict[str, Any], db: Session = Depends(get_db), user: dict = Depends(get_current_user)):
    session = _get_session(db, session_id)
    rule_version_id = payload.get("rule_version_id")
    
    version = db.query(RuleVersion).filter(RuleVersion.id == rule_version_id).first()
    if not version:
        raise HTTPException(status_code=404, detail="Rule version not found")
        
    if version.status != "PENDING_REVIEW":
        raise HTTPException(status_code=400, detail=f"Cannot approve rule in status: {version.status}")
        
    update_rule_version_status(db, version.id, "ACTIVE", "human_reviewer")
    session.status = "COMPLETED"
    db.commit()

    # Retroactively reprocess unresolved events that match this fingerprint
    from app.models.domain import UnresolvedEvent, RawIndex
    from app.services.preservation.vault import vault
    from app.core.queue import event_queue, EventRecord
    import logging

    logger = logging.getLogger(__name__)

    unresolved = db.query(UnresolvedEvent).filter(UnresolvedEvent.fingerprint == session.fingerprint).all()
    reprocessed_count = 0
    for ev in unresolved:
        raw_idx = db.query(RawIndex).filter(RawIndex.trace_id == ev.trace_id).first()
        if raw_idx:
            try:
                raw_bytes = await vault.read_event(raw_idx.source_id, raw_idx.received_at, raw_idx.trace_id)
                record = EventRecord(
                    trace_id=raw_idx.trace_id,
                    source_id=raw_idx.source_id,
                    payload=raw_bytes,
                    byte_length=raw_idx.byte_length
                )
                await event_queue.publish(record)
                db.delete(ev)
                reprocessed_count += 1
            except Exception as e:
                logger.error(f"Failed to reprocess unresolved event {ev.trace_id}: {e}")
    if reprocessed_count > 0:
        db.commit()
        logger.info(f"Retroactively pushed {reprocessed_count} unresolved events to queue for processing.")
    
    return {"status": "ACTIVE", "rule_id": version.rule_id, "version": version.version}
